spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    #url: jdbc:h2:mem:testdb
    #url: jdbc:h2:/Users/lixinhai/test
    #driverClassName: org.h2.Driver
    #username: sa
    #password:
    url: jdbc:mysql://127.0.0.1:3306/axon_test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
